"""
Dynamic Position Sizing based on Volatility
Chapter 3: Dynamic Risk Management
Book 2: Python for Advanced Algorithmic Trading
"""

import numpy as np
import pandas as pd


def calculate_dynamic_position_sizing(df, capital, risk_pct=1.0, multiplier_atr=2.0):
    """
    Calculate dynamic position size based on ATR.
    
    Parameters:
    -----------
    df : pandas DataFrame
        Must contain columns: 'high', 'low', 'close'
    capital : float
        Total account capital
    risk_pct : float, default=1.0
        Percentage of capital to risk per trade
    multiplier_atr : float, default=2.0
        Multiplier for the stop loss distance based on ATR
        
    Returns:
    --------
    pandas DataFrame with added 'stop_pips' and 'lot_size' columns
    """
    df = df.copy()
    
    # Calculate True Range and ATR
    df['tr'] = np.maximum(
        df['high'] - df['low'],
        np.maximum(
            np.abs(df['high'] - df['close'].shift(1)),
            np.abs(df['low'] - df['close'].shift(1))
        )
    )
    df['atr'] = df['tr'].rolling(14).mean()
    
    # Fixed monetary risk
    monetary_risk = capital * (risk_pct / 100)
    
    # Calculate position size for each moment
    # Convert ATR to pips (assuming Forex where 1 pip = 0.0001)
    df['stop_pips'] = df['atr'] * multiplier_atr * 10000 
    
    # Lot size calculation (assuming $10 per pip for a standard lot)
    df['lot_size'] = monetary_risk / (df['stop_pips'] * 10)
    
    # Limit maximum size to avoid ridiculously large positions in low volatility
    df['lot_size'] = df['lot_size'].clip(upper=1.0) # Maximum 1 lot
    
    # Drop NaN values generated by the rolling window
    df = df.dropna(subset=['atr', 'lot_size'])
    
    return df


def compare_fixed_sizing_vs_dynamic(df, capital, risk_pct=1.0):
    """
    Compare fixed sizing vs dynamic sizing by simulating 100 random transactions.
    
    Parameters:
    -----------
    df : pandas DataFrame
        Historical data to calculate the average dynamic lot size
    capital : float
        Total account capital
    risk_pct : float, default=1.0
        Percentage of capital to risk per trade
        
    Returns:
    --------
    dict : Dictionary with the total PnL for both methods
    """
    # Fixed sizing (always 0.5 lots)
    fixed_size = 0.5
    
    # Dynamic sizing (use average size from historical data)
    df_dynamic = calculate_dynamic_position_sizing(df, capital, risk_pct, multiplier_atr=2.0)
    dynamic_size = df_dynamic['lot_size'].mean()
    
    # Simulate 100 random operations
    np.random.seed(42)
    fixed_results = []
    dynamic_results = []
    
    for _ in range(100):
        winner = np.random.random() < 0.60 # 60% win rate
        # Random PnL in pips
        pnl_pips = np.random.uniform(15, 40) if winner else np.random.uniform(-20, -10)
        
        # Fixed sizing PnL (1 lot = $10 per pip)
        pnl_fixed = pnl_pips * fixed_size * 10
        fixed_results.append(pnl_fixed)
        
        # Dynamic sizing PnL
        pnl_dynamic = pnl_pips * dynamic_size * 10
        dynamic_results.append(pnl_dynamic)
        
    pnl_total_fixed = sum(fixed_results)
    pnl_total_dynamic = sum(dynamic_results)
    
    print("=== FIXED VS DYNAMIC POSITION SIZING ===\n")
    print(f"Average dynamic lot size used: {dynamic_size:.2f} lots")
    print(f"Fixed lot size used: {fixed_size} lots\n")
    print(f"Total PnL Fixed Sizing: ${pnl_total_fixed:.2f}")
    print(f"Total PnL Dynamic Sizing: ${pnl_total_dynamic:.2f}")
    
    if pnl_total_fixed != 0:
        improvement = 100 * (pnl_total_dynamic - pnl_total_fixed) / abs(pnl_total_fixed)
        print(f"Improvement with dynamic sizing: {improvement:.1f}%")
    else:
        print("Improvement with dynamic sizing: N/A (Fixed PnL is 0)")
        
    return {
        'fixed_pnl': pnl_total_fixed,
        'dynamic_pnl': pnl_total_dynamic,
        'improvement': improvement if pnl_total_fixed != 0 else 0
    }


# Example usage
if __name__ == "__main__":
    # Create sample data for testing
    np.random.seed(42)
    n_days = 500
    
    # Generate sample OHLC data
    close = 1.1000 + np.cumsum(np.random.randn(n_days) * 0.001)
    high = close + np.random.rand(n_days) * 0.002
    low = close - np.random.rand(n_days) * 0.002
    
    df_sample = pd.DataFrame({
        'open': close,
        'high': high,
        'low': low,
        'close': close
    }, index=pd.date_range(start='2020-01-01', periods=n_days, freq='D'))
    
    # 1. Test Dynamic Position Sizing
    print("="*60)
    print("1. DYNAMIC POSITION SIZING CALCULATION")
    print("="*60)
    df_result = calculate_dynamic_position_sizing(df_sample, capital=10000, risk_pct=1.0)
    print(f"\nFirst 5 rows of calculated lot sizes:")
    print(df_result[['close', 'atr', 'stop_pips', 'lot_size']].head())
    print(f"\nAverage lot size: {df_result['lot_size'].mean():.4f}")
    print(f"Maximum lot size: {df_result['lot_size'].max():.4f}")
    print(f"Minimum lot size: {df_result['lot_size'].min():.4f}")
    
    # 2. Compare Fixed vs Dynamic
    print("\n" + "="*60)
    print("2. COMPARISON: FIXED VS DYNAMIC")
    print("="*60)
    compare_fixed_sizing_vs_dynamic(df_sample, capital=10000, risk_pct=1.0)
